version: "3.8"

services:
  internal-postgres:
    image: postgres:15-alpine
    container_name: internal-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cronjob_db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts/internal:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - cronjob_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cronjob_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  external-postgres:
    image: postgres:15-alpine
    container_name: external-postgres
    environment:
      POSTGRES_USER: external_user
      POSTGRES_PASSWORD: external_pass
      POSTGRES_DB: external_db
    volumes:
      - ./init-scripts/external:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    networks:
      - cronjob_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U external_user -d external_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local

networks:
  cronjob_network:
    driver: bridge
