apiVersion: batch/v1
kind: CronJob
metadata:
  name: user-sync
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: app
              image: cron-job-app:latest
              imagePullPolicy: Never
              command: ["node", "dist/scripts/sync-users.js"]
              env:
                # Banco interno (rodando no Docker Compose)
                - name: DATABASE_HOST
                  value: "host.minikube.internal"
                - name: DATABASE_PORT
                  value: "5432"
                - name: DATABASE_USERNAME
                  value: "postgres"
                - name: DATABASE_PASSWORD
                  value: "postgres"
                - name: DATABASE_NAME
                  value: "cronjob_db"
                # Banco externo (rodando no Docker Compose)
                - name: EXTERNAL_DB_HOST
                  value: "host.minikube.internal"
                - name: EXTERNAL_DB_PORT
                  value: "5433"
                - name: EXTERNAL_DB_USERNAME
                  value: "external_user"
                - name: EXTERNAL_DB_PASSWORD
                  value: "external_pass"
                - name: EXTERNAL_DB_NAME
                  value: "external_db"
          restartPolicy: OnFailure